import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Adam' at '11/23/16 9:04 PM' with Gradle 3.0
 *
 * @author Adam, @date 11/23/16 9:04 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

    }
}
